set DIR=D:\Projects\CSharp\!Personal\GoogleAIChallenge2010\Fanny_Heirdoo Suite V2
copy "%DIR%\Fanny_Heirdoo\bin\Debug\*.exe" "%DIR%\Run" /y
copy "%DIR%\Fanny_Heirdoo\bin\Debug\*.dll" "%DIR%\Run" /y
copy "%DIR%\reference\bin\Debug\*.exe" "%DIR%\Run" /y
copy "%DIR%\BullyBot\bin\Debug\*.exe" "%DIR%\Run" /y
copy "%DIR%\DualBot\bin\Debug\*.exe" "%DIR%\Run" /y
copy "%DIR%\RageBot\bin\Debug\*.exe" "%DIR%\Run" /y
copy "%DIR%\RandomBot\bin\Debug\*.exe" "%DIR%\Run" /y
copy "%DIR%\ProspectorBot\bin\Debug\*.exe" "%DIR%\Run" /y
